spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-site
    username: postgres
    password: postgres
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoshaatsu0222@gmail.com
    password: lhwueartkevkmfgm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
   
  batch:
    # Database schema initialization mode.
    initialize-schema: always
    # Path to the SQL file to use to initialize the database schema.
    schema: classpath:schema-all.sql
  
